drop table if exists clothes CASCADE;
create table clothes
(
    id bigint generated by default as identity,
    type varchar(255),
    gender varchar(255),
    size varchar(255),
    color varchar(255),
    image varchar(255),
    primary key (id)
);